### ISSUE TITLE
Whether  max I ( S , S ′ ; Z ) − I ( S , S ′ ; ϕ ( S ′ ) − ϕ ( S ) )  can be called an Information Bottleneck.

### ISSUE THREAD

**Issue by Jackory** [Princeton-RL/contrastive-successor-features#1]
Having followed the ICLR submission, I believe this is an outstanding work that significantly advances the field of unsupervised skill discovery. However, I have a small question about whether $\max I\left(S, S^{\prime} ; Z\right)-I\left(S, S^{\prime} ; \phi\left(S^{\prime}\right)-\phi(S)\right)$ can be called an Information Bottleneck. In [1], the definition of information bottleneck is $I(Z, Y)-\beta I(Z, X)$. Here, $X $ is the input, $Z$ is the representation, and $Y$ is the label, meaning that minimizing mutual information between $Z$ and $X$ makes $Z$ as compressed as possible, while maximizing information between $Z$ and $Y $ ensures $Z$ retains information relevant to $Y$. However, if we look at your case rigorously, it seems that $\max I\left(\phi(S^\prime)- \phi(S),Z\right)-I\left(S, S^{\prime} ; \phi\left(S^{\prime}\right)-\phi(S)\right)$ should be the information bottleneck, rather than $\max I\left(S, S^{\prime} ; Z\right)-I\left(S, S^{\prime} ; \phi\left(S^{\prime}\right)-\phi(S)\right)$. If I've misunderstood something, I would very much appreciate your clarification.

Reference:

[1] Alexander A. Alemi, Ian Fischer, Joshua V. Dillon, and Kevin Murphy. Deep variational information
bottleneck. In International Conference on Learning Representations, 2017. URL https:
[[//openreview.net/forum?id=HyxQzBceg](notion://openreview.net/forum?id=HyxQzBceg)](notion://openreview.net/forum?id=HyxQzBceg).

**Comment by chongyi-zheng** [comment]
Thanks for the question. There are three explanations for this question. 
1. We note that our variant of information bottleneck $\max_{\pi} I(S, S'; Z) - I(S, S'; \phi(S') - \phi(S))$ is the objective for the policy instead of the representation. We have learned the state representations $\phi(s)$ using the contrastive lower bound. 
2. Our variant of information bottleneck can be understood as _communication channels_ for reconstruction: $(S, S') \rightarrow Z \text{ and } \phi(S') - \phi(S) \rightarrow (S, S')$. Note that the difference of representations of transitions $\phi(s') - \phi(s)$ are pushed towards the corresponding skill $z$ via optimizing the contrastive lower bound. Specifically, the conditional distribution $\phi(s') - \phi(s) \mid z$ converges to a isotropic Gaussian (Fig 2 (b)), meaning that we can relate $\phi(s') - \phi(s) / \parallel \phi(s') - \phi(s) \parallel_2$ to the corresponding $z$. So $Z$ and the corresponding $\phi(S') - \phi(S)$ are the communication channels. We also note that when we set $Y = X$, the regular information bottleneck can also be understood as communication channels for reconstruction: $X \rightarrow Z \rightarrow Y = X$. In this case, the information bottleneck is equivalent to $\beta$-VAE.

3. We call the objective $\max I(S, S'; Z) - I(S, S'; \phi(S') - \phi(S))$ a "variant" of information bottleneck instead of the information bottleneck because it does not follow the regular definition of information bottleneck between three random variables $X \rightarrow Z \rightarrow Y = X$. Our information bottleneck includes four random variables $X = (S, S') \rightarrow Z, \phi(S') - \phi(S) \rightarrow Y = (S, S')$.

Hope these explanations answer your question.

**Comment by Jackory** [comment]
Thank you for your detailed explanation. This has addressed my concerns.
